name: r6_operators_info
description: All Rainbow Six Siege operators.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  sqflite: any
  path_provider: any
  animations: any

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "res/App_icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Лого игры
    - res/R6_Logo.png
    # Иконки атакующих и защитников
    - res/AttackerIcon.png
    - res/DefenderIcon.png
    # Уменьшенные версии иконок сверху без обводки
    - res/MiniAttackerIcon.png
    - res/MiniDefenderIcon.png
    # Флаги стран оперативников
    - res/CountryFlags/
    # База данных со всей нужной информацией о оперативниках
    - res/operators_database.db
    # Ассеты снаряжения оперативников
    - res/Loadout/Ability/
    - res/Loadout/Gadget/
    - res/Loadout/Primary/
    - res/Loadout/Secondary/
    # Nighthaven / ITF (Steel Wave)
    - res/OperatorsData/Ace/
    - res/OperatorsData/Melusi/
    # Unafilliated / REU (Void Edge)
    - res/OperatorsData/Oryx/
    - res/OperatorsData/Iana/
    # Nighthaven (Shifting Tides)
    - res/OperatorsData/Wamai/
    - res/OperatorsData/Kali/
    # APCA / FES (Ember Rise)
    - res/OperatorsData/Amaru/
    - res/OperatorsData/Goyo/
    # Jaeger Corps / Secret Service (Phantom Sight)
    - res/OperatorsData/Nokk/
    - res/OperatorsData/Warden/
    # SASR (Burnt Horizon)
    - res/OperatorsData/Mozzie/
    - res/OperatorsData/Gridlock/
    # GIGR (Wind Bastion)
    - res/OperatorsData/Nomad/
    - res/OperatorsData/Kaid/
    # MPS / The Unit (Grim Sky)
    - res/OperatorsData/Clash/
    - res/OperatorsData/Maverick/
    # G.I.S. (Para Bellum)
    - res/OperatorsData/Maestro/
    - res/OperatorsData/Alibi/
    # GIGN / Spetsnaz (Chimera)
    - res/OperatorsData/Lion/
    - res/OperatorsData/Finka/
    # 707th SMB / G.R.O.M (White Noise)
    - res/OperatorsData/Vigil/
    - res/OperatorsData/Dokkaebi/
    - res/OperatorsData/Zofia/
    # G.R.O.M / S.D.U (Blood Orchid)
    - res/OperatorsData/Ela/
    - res/OperatorsData/Ying/
    - res/OperatorsData/Lesion/
    # G.E.O. (Velvet Shell)
    - res/OperatorsData/Mira/
    - res/OperatorsData/Jackal/
    # S.A.T. (Red Crow)
    - res/OperatorsData/Hibana/
    - res/OperatorsData/Echo/
    # BOPE (Skull Rain)
    - res/OperatorsData/Caveira/
    - res/OperatorsData/Capitao/
    # Navy Seal (Dust Line)
    - res/OperatorsData/Blackbeard/
    - res/OperatorsData/Valkyrie/
    # JTF2 (Black Ice)
    - res/OperatorsData/Buck/
    - res/OperatorsData/Frost/
    # SAS (Release)
    - res/OperatorsData/Mute/
    - res/OperatorsData/Sledge/
    - res/OperatorsData/Smoke/
    - res/OperatorsData/Thatcher/
    # SWAT (Release)
    - res/OperatorsData/Ash/
    - res/OperatorsData/Castle/
    - res/OperatorsData/Pulse/
    - res/OperatorsData/Thermite/
    # GIGN (Release)
    - res/OperatorsData/Montagne/
    - res/OperatorsData/Twitch/
    - res/OperatorsData/Doc/
    - res/OperatorsData/Rook/
    # GSG9 (Release)
    - res/OperatorsData/Jager/
    - res/OperatorsData/Bandit/
    - res/OperatorsData/Blitz/
    - res/OperatorsData/Iq/
    # Spetsnaz (Release)
    - res/OperatorsData/Fuze/
    - res/OperatorsData/Glaz/
    - res/OperatorsData/Tachanka/
    - res/OperatorsData/Kapkan/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
